version: "3.9"
name: blockchain
services:
  node-amd64:
    image: ymhw/blockchain-node-amd64:latest
    environment:
      PORT: 30333
      DEBUG: false
      API_PORT: 8080
    deploy:
      replicas: 16
