name: build and test

on:
  pull_request:
  push:
    branches-ignore:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  golang-ci:
    uses: ./.github/workflows/golang-ci.yml
