name: go

on:
  push:
  pull_request:
    branches:
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: build
      run: |
        make deps
        make build_all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: gotestsum
        run: |
          make install_gotestsum
          make test_ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        run: |
          make install_lint
          make lint
      - name: gofumpt
        run: |
          make install_gofumpt
          make formatcheck
