name: golang-ci

on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: build
      run: |
        go mod download && go mod verify
        make build_amd64
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: gotestsum
        run: |
          make install_gotestsum
          make test_ci
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        run: |
          make install_lint
          make lint
      - name: gofumpt
        run: |
          make install_gofumpt
          make formatcheck
