name: release

on:
  release:
    branches: [master]
    types: [published]

jobs:
 golang-ci:
   uses: ./.github/workflows/golang-ci.yml
 release:
   runs-on: ubuntu-latest
   needs: golang-ci
   steps:
   - uses: actions/checkout@v3
   - uses: docker/setup-qemu-action@v2
   - uses: docker/setup-buildx-action@v2
   - name: Login to Docker Hub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Login to GitHub Container Registry
     uses: docker/login-action@v2
     with:
       registry: ghcr.io
       username: ${{ github.repository_owner }}
       password: ${{ secrets.GITHUB_TOKEN }}
   - name: Build and push
     uses: docker/build-push-action@v3
     with:
       context: .
       file: ./docker/amd64/Dockerfile
       push: true
       tags: ymhw/blockchain-node-amd64:${{  github.ref_name }}


